In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.io.arff import loadarff

### categorical data
categorical variables have discrete values

In [3]:
data, metadata = loadarff('../datasets/adult_census.arff')
adult_census = pd.DataFrame(data)
for col in adult_census.select_dtypes(include='object'):
    adult_census[col] = adult_census[col].str.decode('utf-8')
adult_census = adult_census.drop(columns='education-num')

data = adult_census.drop(columns='class')
target = adult_census['class']
data.head()

,age,workclass,fnlwgt,education,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,25.0,Private,226802.0,11th,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States
1,38.0,Private,89814.0,HS-grad,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States
2,28.0,Local-gov,336951.0,Assoc-acdm,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States
3,44.0,Private,160323.0,Some-college,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States
4,18.0,?,103497.0,Some-college,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States

In [4]:
data[data.dtypes[data.dtypes=='str'].index].head()

,workclass,education,marital-status,occupation,relationship,race,sex,native-country
0,Private,11th,Never-married,Machine-op-inspct,Own-child,Black,Male,United-States
1,Private,HS-grad,Married-civ-spouse,Farming-fishing,Husband,White,Male,United-States
2,Local-gov,Assoc-acdm,Married-civ-spouse,Protective-serv,Husband,White,Male,United-States
3,Private,Some-college,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,United-States
4,?,Some-college,Never-married,?,Own-child,White,Female,United-States

In [5]:
from sklearn.compose import make_column_selector as selector

categorical_cols_selector = selector(dtype_include=str)
categorical_cols = categorical_cols_selector(data)
categorical_cols

['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native-country']

In [6]:
data_categorical = data[categorical_cols]
data_categorical

,workclass,education,marital-status,occupation,relationship,race,sex,native-country
0,Private,11th,Never-married,Machine-op-inspct,Own-child,Black,Male,United-States
1,Private,HS-grad,Married-civ-spouse,Farming-fishing,Husband,White,Male,United-States
2,Local-gov,Assoc-acdm,Married-civ-spouse,Protective-serv,Husband,White,Male,United-States
3,Private,Some-college,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,United-States
4,?,Some-college,Never-married,?,Own-child,White,Female,United-States
...,...,...,...,...,...,...,...,...
48837,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,United-States
48838,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States
48839,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,United-States
48840,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,United-States
48841,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,United-States

no encoding

### encoding categories

#### OneHotEncoder -> linear models 
#### OrdinalEncoder -> tree-based models

* ordinal categories
--> encode each category with a different number

In [7]:
from sklearn.preprocessing import OrdinalEncoder

education_column = data_categorical[['education']]
encoder = OrdinalEncoder().set_output(transform='pandas')
education_encoded = encoder.fit_transform(education_column)
education_encoded

       education
0            1.0
1           11.0
2            7.0
3           15.0
4           15.0
...          ...
48837        7.0
48838       11.0
48839       11.0
48840       11.0
48841       11.0

[48842 rows x 1 columns]

In [8]:
data_encoded = encoder.fit_transform(data_categorical)
data_encoded.head()

,workclass,education,marital-status,occupation,relationship,race,sex,native-country
0,4.0,1.0,4.0,7.0,3.0,2.0,1.0,39.0
1,4.0,11.0,2.0,5.0,0.0,4.0,1.0,39.0
2,2.0,7.0,2.0,11.0,0.0,4.0,1.0,39.0
3,4.0,15.0,2.0,7.0,0.0,2.0,1.0,39.0
4,0.0,15.0,4.0,0.0,3.0,4.0,0.0,39.0

* encoding nominal categories (without assuming any order)

In [9]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
education_encoded = encoder.fit_transform(education_column)
education_encoded.iloc[0]

education_10th            0.0
education_11th            1.0
education_12th            0.0
education_1st-4th         0.0
education_5th-6th         0.0
education_7th-8th         0.0
education_9th             0.0
education_Assoc-acdm      0.0
education_Assoc-voc       0.0
education_Bachelors       0.0
education_Doctorate       0.0
education_HS-grad         0.0
education_Masters         0.0
education_Preschool       0.0
education_Prof-school     0.0
education_Some-college    0.0
Name: 0, dtype: float64

In [10]:
data_encoded = encoder.fit_transform(data_categorical)
data_encoded.head()

,workclass_?,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,education_10th,...,native-country_Portugal,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

### evaluating

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate
from sklearn.pipeline import Pipeline

# using OneHotEncoder
pipe = Pipeline([('encoder', OneHotEncoder(handle_unknown='ignore')), ('model', LogisticRegression(max_iter=500))])
cv_score = cross_validate(pipe, data_categorical, target)['test_score']
f'accuracy is {cv_score.mean():.4f} ± {cv_score.std():.4f}'

'accuracy is 0.8328 ± 0.0026'

In [34]:
pipe = Pipeline([('encoder', OneHotEncoder(min_frequency=25, handle_unknown='infrequent_if_exist')), ('model', LogisticRegression(max_iter=500))])
cv_score = cross_validate(pipe, data_categorical, target)['test_score']
f'accuracy is {cv_score.mean():.4f} ± {cv_score.std():.4f}'

'accuracy is 0.8330 ± 0.0024'

### ordinal encoder vs one hot encoder

In [50]:
pipe.named_steps

{'encoder': OneHotEncoder(handle_unknown='infrequent_if_exist', min_frequency=25),
 'model': LogisticRegression(max_iter=500)}

In [ ]:
from sklearn.base import clone

def comparison_report(model):
    pipe_ordinal = Pipeline([('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)), ('model', clone(model))])
    pipe_one_hot = Pipeline([('encoder', OneHotEncoder(handle_unknown='ignore')), ('model', clone(model))])
    cv_ordinal = cross_validate(pipe_ordinal, data_categorical, target, error_score="raise")
    cv_one_hot = cross_validate(pipe_one_hot, data_categorical, target, error_score="raise")
    print(f"{pipe_ordinal.named_steps['encoder']} -> {cv_ordinal['test_score'].mean():.4f} ± {cv_ordinal['test_score'].std():.4f}")
    print(f"{pipe_one_hot.named_steps['encoder']} -> {cv_one_hot['test_score'].mean():.4f} ± {cv_one_hot['test_score'].std():.4f}")

* logistic regression

In [52]:
comparison_report(LogisticRegression(max_iter=500))

OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1) -> 0.7555 ± 0.0015
OneHotEncoder(handle_unknown='ignore') -> 0.8328 ± 0.0026

* random forest

In [53]:
from sklearn.ensemble import RandomForestClassifier

comparison_report(RandomForestClassifier(n_estimators=100))

OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1) -> 0.8252 ± 0.0019
OneHotEncoder(handle_unknown='ignore') -> 0.8271 ± 0.0029

* decision tree

In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier

model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=100,
    random_state=42
)

comparison_report(model)

OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1) -> 0.8288 ± 0.0028
OneHotEncoder(handle_unknown='ignore') -> 0.8265 ± 0.0018